# 应用名称
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # 当前路由的唯一标识
        - id: provider-service-route
          # 转发到服务器的地址
          uri: http://127.0.0.1:29091
          # 断言，当前路由转发的规则（拦截规则）
          predicates:
            - Path=/user/**
server:
  port: 10010
# 注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
# 配置路由转发的规则

