# 多环境的配置文件
# 第一种，yml配置文件中，多块(---)
# 第二种，通过配置文件的命名，application-[dev,pro,test].yml

# 激活多环境配置文件中的一个
spring.profiles.active: dev

# 松散绑定
#wong.spring-boot.one-example: dilireba
#wong.springBoot.oneExample: dilireba
wong.spring_boot.one_example: dilireba

#---
## 开发环境的配置
#server.port: 48081
#spring.profiles: dev
#---
## 测试环境的配置
#server.port: 49090
#spring.profiles: test
#---
## 生产环境的配置
#server.port: 80
#spring.profiles: pro